### ISSUE TITLE
Documentación

### ISSUE THREAD

**Issue by DanBaDo** [tmayolgomila/instagram-photo-feed-bootstrap#1]
Muy bien el código.
Tenemos que empezar a darle valor.
Usa el fichero README.md del proyecto para hacer una pequeña presentación del mismo: tecnologías, objetivos, cuestiones reseñables, una pequeña memoria...
Ayuda a darle un sentido y más valor a tu repositorio.

**Comment by tmayolgomila** [comment]
Presentación y comentarios realizados sobre el README
